/**
 * Prisma configuration — tells Prisma where the schema and database live.
 *
 * schema: path to schema.prisma (defines tables and relations).
 * migrations: folder for database migration history.
 * datasource.url: SQLite file path from DATABASE_URL in .env.
 */
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
