/**
 * Prisma Configuration — project-level settings for the Prisma CLI.
 *
 * ROLE IN THE APP:
 *   Prisma 6+ uses prisma.config.ts (instead of only schema.prisma) to locate
 *   the schema file, migration folder, and database connection URL. The CLI
 *   reads this when you run `prisma migrate`, `prisma db seed`, etc.
 *
 * KEY SETTINGS:
 *   schema       — prisma/schema.prisma defines User, Product, Order, Coupon…
 *   migrations   — version-controlled SQL migration history
 *   datasource.url — SQLite path from DATABASE_URL env var (file:./dev.db)
 *
 * PI INTERVIEW TALKING POINTS:
 *   - Prisma schema = single source of truth for DB structure + TS types
 *   - Migrations let you evolve schema safely across dev/staging/prod
 *   - dotenv/config loads .env so DATABASE_URL is available to the CLI
 */
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
